# Generated by Django 5.2.7 on 2025-11-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlycare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='assigned', max_length=20),
        ),
    ]
