# Generated by Django 5.2.7 on 2025-10-25 14:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('earlycare', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('achievement', 'Achievement'), ('participation', 'Participation'), ('improvement', 'Improvement'), ('milestone', 'Milestone'), ('special', 'Special Recognition')], default='achievement', max_length=20)),
                ('icon', models.CharField(help_text='Icon class or image name', max_length=50)),
                ('color', models.CharField(default='#FFD700', help_text='Hex color code', max_length=7)),
                ('points_value', models.IntegerField(default=10, help_text='Points awarded for this badge')),
                ('criteria', models.TextField(default='Complete activities to earn this badge.', help_text='Description of how to earn this badge')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['points_value', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('math', 'Mathematics'), ('science', 'Science'), ('art', 'Art & Creativity'), ('music', 'Music'), ('physical', 'Physical Activity'), ('social', 'Social Skills'), ('cognitive', 'Cognitive Development'), ('language', 'Language Development')], max_length=20)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Easy'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1)),
                ('instructions', models.TextField(default='Instructions will be provided here.', help_text='Step-by-step instructions')),
                ('materials_needed', models.TextField(blank=True, help_text='Required materials')),
                ('estimated_duration', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('age_range_min', models.IntegerField(default=0, help_text='Minimum age in months')),
                ('age_range_max', models.IntegerField(default=60, help_text='Maximum age in months')),
                ('learning_objectives', models.TextField(default='Learning objectives will be defined here.', help_text='What children will learn')),
                ('skills_developed', models.TextField(default='Skills developed will be listed here.', help_text='Skills this activity develops')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ActivityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('completed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='learnlytics.activity')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_assignments', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_activities', to='earlycare.child')),
            ],
            options={
                'verbose_name': 'Activity Assignment',
                'verbose_name_plural': 'Activity Assignments',
                'ordering': ['-assigned_date'],
                'unique_together': {('child', 'activity')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='Performance score')),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in minutes')),
                ('attempts', models.IntegerField(default=1, help_text='Number of attempts')),
                ('accuracy', models.FloatField(default=0.0, help_text='Accuracy percentage')),
                ('completion_rate', models.FloatField(default=0.0, help_text='Completion rate percentage')),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learnlytics.activity')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='earlycare.child')),
            ],
            options={
                'verbose_name': 'Performance Metric',
                'verbose_name_plural': 'Performance Metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('child_progress', 'Child Progress Report'), ('class_performance', 'Class Performance Report'), ('activity_analytics', 'Activity Analytics Report'), ('badge_earnings', 'Badge Earnings Report'), ('custom', 'Custom Report')], max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(help_text='Start date for report data')),
                ('end_date', models.DateField(help_text='End date for report data')),
                ('summary', models.TextField(default='Report summary will be provided here.', help_text='Executive summary')),
                ('data', models.JSONField(blank=True, default=None, help_text='Report data in JSON format', null=True)),
                ('key_findings', models.TextField(default='Key findings will be documented here.', help_text='Key findings and insights')),
                ('recommendations', models.TextField(default='Recommendations will be provided here.', help_text='Recommendations based on data')),
                ('chart_data', models.JSONField(blank=True, default=None, help_text='Chart configuration and data', null=True)),
                ('is_exported', models.BooleanField(default=False)),
                ('export_format', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('export_file', models.FileField(blank=True, default=None, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='earlycare.child')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChildBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('awarded_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awarded_badges', to=settings.AUTH_USER_MODEL)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_badges', to='learnlytics.badge')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='earlycare.child')),
                ('earned_for_activity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learnlytics.activityassignment')),
            ],
            options={
                'verbose_name': 'Child Badge',
                'verbose_name_plural': 'Child Badges',
                'ordering': ['-earned_date'],
                'unique_together': {('child', 'badge')},
            },
        ),
    ]
